FORMAT: 1A

# Tic Endpoints
Dashboards are collections of users' Datapoints.

# Group Dashboards
Dashboards related resources of the **Dashboards API**

## Dashboards Collection [/dashboards/]
### List all user's Dasbhoards [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Dashboard [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Dashboards [/dashboards/{id}]
A single Dashboard object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove Dashboard [DELETE]
+ Response 204
